Setup CD with Qovery
deps-rs/deps.rs pull request #61
Opened 2020-10-03 11:53 UTC by cecton

Not much to do actually. Everything is automagic

2020-10-05 11:00 UTC, berkus approved these changes
lgtm,

however i would fixup the four comments about custom domain into one?

I follow the words of someone on the internets (whom I cannot find anymore) that a projects git history should reflect what you want to achieve, not how you got there. Even though knowing how you got there is also quite important, so I usually object against just squashing the entire PR - in our team we adopted that commits in PRs should be sorted, logically grouped and describing atomic changes; but after merge they will stay and keep this set of atomic changes for the repo history.

2020-10-05 11:01 UTC, berkus commented
Ah, I see it's still in progress, so will be cleaned up in due time, sorry for making a fuss.

2020-10-05 11:31 UTC, cecton commented
> Ah, I see it's still in progress, so will be cleaned up in due time, sorry for making a fuss.

yeah and I squash merge at the end :stuck_out_tongue_closed_eyes:

2020-10-05 11:57 UTC, paolobarbolini requested changes
We have to set the `BASE_URL` environment variable, else `http://localhost:8080` will be used as the base url for all generated urls.

https://github.com/deps-rs/deps.rs/blob/8b58821bebdf881551f7709ff8d0c84d54ea1103/src/server/mod.rs#L362-L363

2020-10-05 13:26 UTC, cecton commented
> `http://localhost:8080` will be used as the base url for all urls.

what do you mean for all urls?

It's a container. They can all use the same port

2020-10-05 13:40 UTC, robjtede commented
`SELF_BASE_URL` is used for link generation so when hosted on a domain it needs to match that domain lest the links go to localhost.

2020-10-05 14:12 UTC, cecton commented
Oh ok thanks!!

2020-10-23 17:00 UTC, paolobarbolini approved these changes
LGTM

2020-10-23 17:13 UTC, merged

2020-10-23 17:14 UTC, robjtede commented on .dockerignore
> +/.qovery.yml
```suggestion
target
Dockerfile
```

2020-10-23 17:14 UTC, robjtede commented on Dockerfile
> +    rm -rf /var/lib/apt/lists/*
using something like [minideb](https://github.com/bitnami/minideb) simplifies this to
```
install_packages libssl-dev
```

2020-10-23 17:14 UTC, robjtede commented on Dockerfile
> +FROM buildpack-deps:buster as build
what's the advantage of this manual approach over just using `rust:stable` ?

2020-10-24 09:05 UTC, cecton commented on Dockerfile
> +FROM buildpack-deps:buster as build
Our project is made to use nightly and a very specific version of it: https://github.com/deps-rs/deps.rs/blob/main/rust-toolchain

It would be great if we can drop this constraint and use only stable.

2020-10-24 09:06 UTC, cecton commented on .dockerignore
> +/.qovery.yml
Oops :sweat:

2020-10-24 09:07 UTC, cecton commented on Dockerfile
> +    rm -rf /var/lib/apt/lists/*
Don't hesitate to change it later if you want

2020-10-24 14:35 UTC, robjtede commented on Dockerfile
> +FROM buildpack-deps:buster as build
Oh right I forgot that we're still constrained by maud. Ok no problem.