Display rustsec information on page
deps-rs/deps.rs pull request #96
Opened 2021-01-31 17:16 UTC by Feliix42

This PR adds functionality to close #75.
RustSec advisories affecting a repository are now listed with some additional information at the bottom of the page. This encompasses the description of the CVE, a list of unaffected and fixed versions as well as a link to the RustSec page (which I have to generate manually based on their URL scheme so pray that this will never change).

## Dependency changes
- I bumped the `rustsec` crate version to the latest release. Since I was going to touch most of the code using this crate anyway I thought using the most up-to-date version would be wise.
- I added `pulldown-cmark` as a dependency to render the CVE descriptions (which are markdown). This might be a bit overkill, but if anybody knows a maintained, well-functioning, small Markdown renderer raise your hands. 😄

## Code changes
I significantly expanded `src/server/views/html/status.rs` to add the functionality. If someone feels like cleaning this up or has suggestions for cleaner code, do speak up :)

2021-01-31 17:28 UTC, paolobarbolini commented on src/models/crates.rs
> +    pub vulnerabilities: Option<Vec<Advisory>>,
This could simply be a `Vec`, since we can already check if it's empty to know if there are vulnerabilities or not.

2021-01-31 17:28 UTC, Feliix42 commented
I should add that I had to manually override some CSS behavior. Our version of Bulma seems to be badly outdated and does not support some of the spacing rules you'd normally use.
Judging from the commit history the CSS has not been updated since 2018. Someone who's more experienced in these things could give this a hand at some point. :)

As for testing this: `bat` seems to have some insecure dependencies, that's what I used for development.

2021-01-31 17:29 UTC, paolobarbolini commented on src/engine/machines/analyzer.rs
> +                        Some(vulnerabilities.drain(..).map(|v| v.to_owned()).collect());
`.into_iter()` could be a more idiomatic way of iterating over it.

2021-01-31 17:30 UTC, paolobarbolini commented on src/server/views/html/status.rs
> +    let vulnerabilities: Vec<&Advisory> = vulnerabilities.drain(..).flatten().collect();
Same here

2021-01-31 17:35 UTC, paolobarbolini commented on src/server/views/html/status.rs
> +                .collect(),
These could use `extend` so that we won't need to unnecessarily `collect`.

2021-01-31 17:36 UTC, paolobarbolini requested changes
Looks good, thanks for taking the time!

It looks like having multiple imports across different crates in the same workspace will result into the same vulnerability appearing multiple times. (see http://localhost:8080/repo/github/SergioBenitez/Rocket).

I can take a look at the css after this is merged.

2021-01-31 18:09 UTC, Feliix42 commented on src/server/views/html/status.rs
> +    let vulnerabilities: Vec<&Advisory> = vulnerabilities.drain(..).flatten().collect();
Each single dependency of a crate contains a `Vec<&Advisory>`. After the previous lines I'm left with a `Vec<Vec<&Advisory>>` that needs to be flattened. I'll probably look over that piece of code once more and turn the `Vec<T>` into a `HashSet<T>` to deduplicate the advisories.

2021-01-31 18:20 UTC, Enet4 reviewed
All in all, I agree with @paolobarbolini's suggestions. Another example of redundant advisory entries is my repository [dicom-rs](http://localhost:8080/repo/github/Enet4/dicom-rs).

While trying this out, I noticed that the deps.rs installation in deps.rs indicates no security vulnerabilities in this repository, whereas a fresh installation locally reports [RUSTSEC-2021-0003](https://rustsec.org/advisories/RUSTSEC-2021-0003.html) due to `smallvec`. This vulnerability was reported in 2021-01-08, so one would expect it to be considered by deps.rs by now. So far this does not seem to be related to this PR, but to , and it has got a bit in the way of trying out these changes. They look great, by the way! I agree to merge them once the requested changes are in.

2021-01-31 19:41 UTC, Feliix42 commented on src/server/views/html/status.rs
> +    let vulnerabilities: Vec<&Advisory> = vulnerabilities.drain(..).flatten().collect();
I ended up not being able to remove that line but cleaned up the comment to make clear what the line is for.

2021-01-31 19:41 UTC, Feliix42 commented on src/server/views/html/status.rs
> +                .collect(),
Done!

2021-01-31 19:42 UTC, Feliix42 commented on src/engine/machines/analyzer.rs
> +                        Some(vulnerabilities.drain(..).map(|v| v.to_owned()).collect());
Right. I somehow always overlooked that function. Thanks for pointing that out :D

2021-01-31 19:46 UTC, Feliix42 commented
The idea of using a `HashSet` for deduplication was all nice and dandy, but since `Advisory` does not implement traits like `Ord` or `Hash`, I had to make the detour of putting it all into a `Vec`, sorting it and deduping that. But it works. All comments have been addressed. 

Thanks @Enet4 for the praise, UI and web design are not exactly my forte. 😄

2021-01-31 20:38 UTC, Enet4 approved these changes
> The idea of using a `HashSet` for deduplication was all nice and dandy, but since `Advisory` does not implement traits like `Ord` or `Hash`, I had to make the detour of putting it all into a Vec, sorting it and deduping that. But it works. All comments have been addressed.

It is fine. Had we already been using `itertools`, I would've recommended to use `unique_by` on the iterator, but it is unclear if it's worth adding another dependency just for this.

2021-02-01 17:18 UTC, paolobarbolini approved these changes
LGTM

2021-02-01 17:33 UTC, robjtede approved these changes

2021-02-01 18:46 UTC, merged